services:
  dev:
    build:
      context: .
      dockerfile: src/BeloteEngine.Api/DockerfileDev
    image: beloteengine:dev
    container_name: BeloteEngine-dev
    ports:
      - "8081:8081"
    volumes:
      - ./:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - belote-network

  prod:
    build:
      context: .
      dockerfile: src/BeloteEngine.Api/Dockerfile
    container_name: BeloteEngine-prod
    image: beloteengine:prod
    ports:
      - "8082:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedOrigins=${ALLOWED_ORIGINS:-http://localhost:3000}
      - AllowedHosts=${ALLOWED_HOSTS:-*}
    restart: unless-stopped
    networks:
      - belote-network

networks:
  belote-network:
    driver: bridge
